// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: upload.proto

package server

import (
	"context"

	"upload/internal/logic"
	"upload/internal/svc"
	"upload/pb/upload"
)

type UploadServer struct {
	svcCtx *svc.ServiceContext
	upload.UnimplementedUploadServer
}

func NewUploadServer(svcCtx *svc.ServiceContext) *UploadServer {
	return &UploadServer{
		svcCtx: svcCtx,
	}
}

func (s *UploadServer) FileUpload(ctx context.Context, in *upload.FileUploadReq) (*upload.FileUploadRes, error) {
	l := logic.NewFileUploadLogic(ctx, s.svcCtx)
	return l.FileUpload(in)
}
